import re
import emoji
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.tokenize import word_tokenize
from nltk.corpus import wordnet

# Text preprocessor class to clean and preprocess text data
class TextPreprocessor:
    def __init__(self):

        # Dictionary of English contractions
        self.contractions_dict = {
            "ain't": "is not",
            "aren't": "are not",
            "can't": "cannot",
            "can't've": "cannot have",
            "'cause": "because",
            "could've": "could have",
            "couldn't": "could not",
            "couldn't've": "could not have",
            "didn't": "did not",
            "doesn't": "does not",
            "don't": "do not",
            "hadn't": "had not",
            "hadn't've": "had not have",
            "hasn't": "has not",
            "haven't": "have not",
            "he'd": "he would",
            "he'd've": "he would have",
            "he'll": "he will",
            "he'll've": "he will have",
            "he's": "he is",
            "how'd": "how did",
            "how'd'y": "how do you",
            "how'll": "how will",
            "how's": "how is",
            "i'd": "I would",
            "i'd've": "I would have",
            "i'll": "I will",
            "i'll've": "I will have",
            "i'm": "I am",
            "i've": "I have",
            "isn't": "is not",
            "it'd": "it would",
            "it'd've": "it would have",
            "it'll": "it will",
            "it'll've": "it will have",
            "it's": "it is",
            "let's": "let us",
            "ma'am": "madam",
            "mayn't": "may not",
            "might've": "might have",
            "mightn't": "might not",
            "mightn't've": "might not have",
            "must've": "must have",
            "mustn't": "must not",
            "mustn't've": "must not have",
            "needn't": "need not",
            "needn't've": "need not have",
            "o'clock": "of the clock",
            "oughtn't": "ought not",
            "oughtn't've": "ought not have",
            "shan't": "shall not",
            "sha'n't": "shall not",
            "shan't've": "shall not have",
            "she'd": "she would",
            "she'd've": "she would have",
            "she'll": "she will",
            "she'll've": "she will have",
            "she's": "she is",
            "should've": "should have",
            "shouldn't": "should not",
            "shouldn't've": "should not have",
            "so've": "so have",
            "so's": "so is",
            "that'd": "that would",
            "that'd've": "that would have",
            "that's": "that is",
            "there'd": "there would",
            "there'd've": "there would have",
            "there's": "there is",
            "they'd": "they would",
            "they'd've": "they would have",
            "they'll": "they will",
            "they'll've": "they will have",
            "they're": "they are",
            "they've": "they have",
            "to've": "to have",
            "wasn't": "was not",
            "we'd": "we would",
            "we'd've": "we would have",
            "we'll": "we will",
            "we'll've": "we will have",
            "we're": "we are",
            "we've": "we have",
            "weren't": "were not",
            "what'll": "what will",
            "what'll've": "what will have",
            "what're": "what are",
            "what's": "what is",
            "what've": "what have",
            "when's": "when is",
            "when've": "when have",
            "where'd": "where did",
            "where's": "where is",
            "where've": "where have",
            "who'll": "who will",
            "who'll've": "who will have",
            "who's": "who is",
            "who've": "who have",
            "why's": "why is",
            "why've": "why have",
            "will've": "will have",
            "won't": "will not",
            "won't've": "will not have",
            "would've": "would have",
            "wouldn't": "would not",
            "wouldn't've": "would not have",
            "y'all": "you all",
            "y'all'd": "you all would",
            "y'all'd've": "you all would have",
            "y'all're": "you all are",
            "y'all've": "you all have",
            "you'd": "you would",
            "you'd've": "you would have",
            "you'll": "you will",
            "you'll've": "you will have",
            "you're": "you are",
            "you've": "you have"
        }

        # Dictionary of chat words
        self.chat_words = {
            "AFAIK": "As Far As I Know",
            "AFK": "Away From Keyboard",
            "ASAP": "As Soon As Possible",
            "ATK": "At The Keyboard",
            "ATM": "At The Moment",
            "A3": "Anytime, Anywhere, Anyplace",
            "BAK": "Back At Keyboard",
            "BBL": "Be Back Later",
            "BBS": "Be Back Soon",
            "BFN": "Bye For Now",
            "B4N": "Bye For Now",
            "BRB": "Be Right Back",
            "BRT": "Be Right There",
            "BTW": "By The Way",
            "B4": "Before",
            "B4N": "Bye For Now",
            "CU": "See You",
            "CUL8R": "See You Later",
            "CYA": "See You",
            "FAQ": "Frequently Asked Questions",
            "FC": "Fingers Crossed",
            "FWIW": "For What It's Worth",
            "FYI": "For Your Information",
            "GAL": "Get A Life",
            "GG": "Good Game",
            "GN": "Good Night",
            "GMTA": "Great Minds Think Alike",
            "GR8": "Great!",
            "G9": "Genius",
            "IC": "I See",
            "ICQ": "I Seek you (also a chat program)",
            "ILU": "ILU: I Love You",
            "IMHO": "In My Honest/Humble Opinion",
            "IMO": "In My Opinion",
            "IOW": "In Other Words",
            "IRL": "In Real Life",
            "KISS": "Keep It Simple, Stupid",
            "LDR": "Long Distance Relationship",
            "LMAO": "Laugh My A.. Off",
            "LOL": "Laughing Out Loud",
            "LTNS": "Long Time No See",
            "L8R": "Later",
            "MTE": "My Thoughts Exactly",
            "M8": "Mate",
            "NRN": "No Reply Necessary",
            "OIC": "Oh I See",
            "PITA": "Pain In The A..",
            "PRT": "Party",
            "PRW": "Parents Are Watching",
            "QPSA?": "Que Pasa?",
            "ROFL": "Rolling On The Floor Laughing",
            "ROFLOL": "Rolling On The Floor Laughing Out Loud",
            "ROTFLMAO": "Rolling On The Floor Laughing My A.. Off",
            "SK8": "Skate",
            "STATS": "Your sex and age",
            "ASL": "Age, Sex, Location",
            "THX": "Thank You",
            "TTFN": "Ta-Ta For Now!",
            "TTYL": "Talk To You Later",
            "U": "You",
            "U2": "You Too",
            "U4E": "Yours For Ever",
            "WB": "Welcome Back",
            "WTF": "What The F...",
            "WTG": "Way To Go!",
            "WUF": "Where Are You From?",
            "W8": "Wait...",
            "7K": "Sick:-D Laugher",
            "TFW": "That feeling when",
            "MFW": "My face when",
            "MRW": "My reaction when",
            "IFYP": "I feel your pain",
            "TNTL": "Trying not to laugh",
            "JK": "Just kidding",
            "IDC": "I don't care",
            "ILY": "I love you",
            "IMU": "I miss you",
            "ADIH": "Another day in hell",
            "ZZZ": "Sleeping, bored, tired",
            "WYWH": "Wish you were here",
            "TIME": "Tears in my eyes",
            "BAE": "Before anyone else",
            "FIMH": "Forever in my heart",
            "BSAAW": "Big smile and a wink",
            "BWL": "Bursting with laughter",
            "BFF": "Best friends forever",
            "CSL": "Can't stop laughing"
        }

        # List of additional HTML terms
        self.additional_html_terms = [
            'br', 'hr', 'a', 'img', 'div', 'span', 'p', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
            'strong', 'em', 'u', 'i', 'b', 'ul', 'ol', 'li', 'table', 'tr', 'th', 'td', 'tbody',
            'thead', 'tfoot', 'blockquote', 'code', 'pre', 'q', 'cite', 'abbr', 'acronym',
            'address', 'article', 'aside', 'audio', 'bdi', 'bdo', 'canvas', 'caption', 'col',
            'colgroup', 'datalist', 'dd', 'del', 'details', 'dfn', 'dialog', 'dl', 'dt', 'figcaption',
            'figure', 'footer', 'header', 'kbd', 'legend', 'main', 'map', 'mark', 'meter', 'nav',
            'noscript', 'object', 'optgroup', 'option', 'output', 'progress', 'rp', 'rt', 'ruby',
            's', 'samp', 'section', 'select', 'small', 'source', 'strong', 'sub', 'summary', 'sup',
            'time', 'title', 'track', 'var', 'video', 'wbr'
        ]

        # List of emotions
        self.emotions_dict = {
            "victimized": "cheated",
            "accused": "cheated",
            "acquitted": "singled out",
            "adorable": "loved",
            "adored": "loved",
            "affected": "attracted",
            "afflicted": "sad",
            "aghast": "fearful",
            "agog": "attracted",
            "agonized": "sad",
            "alarmed": "fearful",
            "amused": "happy",
            "angry": "angry",
            "anguished": "sad",
            "animated": "happy",
            "annoyed": "angry",
            "anxious": "attracted",
            "apathetic": "bored",
            "appalled": "angry",
            "appeased": "singled out",
            "appreciated": "esteemed",
            "apprehensive": "fearful",
            "approved of": "loved",
            "ardent": "lustful",
            "aroused": "lustful",
            "attached": "attached",
            "attracted": "attracted",
            "autonomous": "independent",
            "awed": "fearful",
            "awkward": "embarrassed",
            "beaten down": "powerless",
            "beatific": "happy",
            "belonging": "attached",
            "bereaved": "sad",
            "betrayed": "cheated",
            "bewildered": "surprise",
            "bitter": "angry",
            "blissful": "happy",
            "blithe": "happy",
            "blocked": "powerless",
            "blue": "sad",
            "boiling": "angry",
            "bold": "fearless",
            "bored": "bored",
            "brave": "fearless",
            "bright": "happy",
            "brisk": "happy",
            "calm": "safe",
            "capable": "adequate",
            "captivated": "attached",
            "careless": "powerless",
            "categorized": "singled out",
            "cautious": "fearful",
            "certain": "fearless",
            "chagrined": "belittled",
            "challenged": "attracted",
            "chastised": "hated",
            "cheated": "cheated",
            "cheerful": "happy",
            "cheerless": "sad",
            "cheery": "happy",
            "cherished": "attached",
            "chicken": "fearful",
            "cocky": "independent",
            "codependent": "codependent",
            "coerced": "cheated",
            "comfortable": "happy",
            "common": "average",
            "competent": "adequate",
            "complacent": "apathetic",
            "composed": "adequate",
            "concerned": "attracted",
            "confident": "adequate",
            "confused": "surprise",
            "connected": "attached",
            "conned": "cheated",
            "consumed": "obsessed",
            "contented": "happy",
            "controlled": "powerless",
            "convivial": "happy",
            "cornered": "entitled",
            "courageous": "fearless",
            "cowardly": "fearful",
            "craving": "attracted",
            "crestfallen": "sad",
            "criticized": "hated",
            "cross": "angry",
            "cross-examined": "singled out",
            "crushed": "sad",
            "curious": "attracted",
            "cut off": "alone",
            "daring": "fearless",
            "dark": "sad",
            "dedicated": "attracted",
            "defeated": "powerless",
            "defenseless": "fearful",
            "degraded": "belittled",
            "dejected": "sad",
            "depressed": "sad",
            "deserted": "hated",
            "desirable": "loved",
            "despondent": "sad",
            "detached": "alone",
            "determined": "focused",
            "diminished": "belittled",
            "disappointed": "demoralized",
            "discarded": "hated",
            "disconsolate": "sad",
            "discontented": "sad",
            "discounted": "belittled",
            "discouraged": "powerless",
            "disgraced": "belittled",
            "disgusted": "angry",
            "disheartened": "demoralized",
            "disillusioned": "demoralized",
            "disjointed": "derailed",
            "dismal": "sad",
            "dismayed": "fearful",
            "disoriented": "derailed",
            "disparaged": "cheated",
            "displeased": "sad",
            "disrespected": "belittled",
            "distressed": "sad",
            "distrustful": "anxious",
            "dolorous": "sad",
            "doubtful": "fearful",
            "down": "sad",
            "downhearted": "sad",
            "dreadful": "sad",
            "dreary": "sad",
            "dubious": "anxious",
            "dull": "sad",
            "duped": "cheated",
            "eager": "attracted",
            "earnest": "attracted",
            "ecstatic": "happy",
            "elated": "happy",
            "embarrassed": "embarrassed",
            "empathetic": "attached",
            "enchanted": "attracted",
            "encouraged": "adequate",
            "engrossed": "attracted",
            "enraged": "angry",
            "enterprising": "fearless",
            "enthusiastic": "happy",
            "entrusted": "loved",
            "esteemed": "esteemed",
            "excited": "happy",
            "excluded": "alone",
            "exempt": "entitled",
            "exhausted hopeless": "powerless",
            "exhilarated": "happy",
            "exploited": "cheated",
            "exposed": "fearful",
            "fabulous": "ecstatic",
            "fainthearted": "fearful",
            "fantastic": "ecstatic",
            "fascinated": "attracted",
            "favored": "entitled",
            "fearful": "fearful",
            "fervent": "attracted",
            "fervid": "attracted",
            "festive": "happy",
            "flat": "sad",
            "focused": "focused",
            "forced": "powerless",
            "forsaken": "hated",
            "framed": "cheated",
            "free": "free",
            "free & easy": "happy",
            "frightened": "fearful",
            "frisky": "happy",
            "frustrated": "angry",
            "full of anticipation": "attracted",
            "full of ennui": "apathetic",
            "fuming": "angry",
            "funereal": "sad",
            "furious": "angry",
            "gallant": "fearless",
            "genial": "happy",
            "glad": "happy",
            "gleeful": "happy",
            "gloomy": "sad",
            "glum": "sad",
            "grief-stricken": "sad",
            "grieved": "sad",
            "guilt": "sad",
            "guilty": "singled out",
            "happy": "happy",
            "hardy": "fearless",
            "heartbroken": "sad",
            "heavyhearted": "sad",
            "hesitant": "fearful",
            "high-spirited": "happy",
            "hilarious": "happy",
            "hopeful": "attracted",
            "horny": "lustful",
            "horrified": "fearful",
            "hot and bothered": "lustful",
            "humiliated": "sad",
            "humorous": "happy",
            "hurt": "sad",
            "hysterical": "fearful",
            "ignored": "hated",
            "ill at ease": "sad",
            "immobilized": "apathetic",
            "immune": "entitled",
            "important": "happy",
            "impotent": "powerless",
            "imprisoned": "entitled",
            "in a huff": "angry",
            "in a stew": "angry",
            "in control": "adequate",
            "in fear": "fearful",
            "in pain": "sad",
            "in the dumps": "sad",
            "in the zone": "focused",
            "incensed": "angry",
            "included": "attached",
            "indecisive": "anxious",
            "independent": "free",
            "indignant": "angry",
            "infatuated": "lustful",
            "inflamed": "angry",
            "injured": "sad",
            "inquisitive": "attracted",
            "insecure": "codependent",
            "insignificant": "belittled",
            "intent": "attracted",
            "interested": "attracted",
            "interrogated": "singled out",
            "intrigued": "attracted",
            "irate": "angry",
            "irresolute": "fearful",
            "irresponsible": "powerless",
            "irritated": "angry",
            "isolated": "alone",
            "jaunty": "happy",
            "jocular": "happy",
            "jolly": "happy",
            "jovial": "happy",
            "joyful": "happy",
            "joyless": "sad",
            "joyous": "happy",
            "jubilant": "happy",
            "justified": "singled out",
            "keen": "attracted",
            "labeled": "singled out",
            "lackadaisical": "bored",
            "lazy": "apathetic",
            "left out": "hated",
            "let down": "hated",
            "lethargic": "apathetic",
            "lied to": "cheated",
            "lighthearted": "happy",
            "liked": "attached",
            "lively": "happy",
            "livid": "angry",
            "lonely": "alone",
            "lonesome": "alone",
            "lost": "lost",
            "loved": "attached",
            "low": "sad",
            "lucky": "happy",
            "lugubrious": "sad",
            "macho": "independent",
            "mad": "angry",
            "melancholy": "sad",
            "menaced": "fearful",
            "merry": "happy",
            "mirthful": "happy",
            "misgiving": "fearful",
            "misunderstood": "alone",
            "moody": "sad",
            "moping": "sad",
            "motivated": "attracted",
            "mournful": "sad",
            "needed": "attracted",
            "needy": "codependent",
            "nervous": "fearful",
            "obligated": "powerless",
            "obsessed": "obsessed",
            "offended": "angry",
            "oppressed": "sad",
            "optionless": "entitled",
            "ordinary": "average",
            "organized": "adequate",
            "out of control": "powerless",
            "out of sorts": "sad",
            "outmaneuvered": "entitled",
            "outraged": "angry",
            "overjoyed": "happy",
            "overlooked": "hated",
            "overwhelmed": "powerless",
            "panicked": "fearful",
            "passionate": "lustful",
            "passive": "apathetic",
            "pathetic": "sad",
            "peaceful": "safe",
            "pensive": "anxious",
            "perplexed": "anxious",
            "phobic": "fearful",
            "playful": "happy",
            "pleased": "happy",
            "powerless": "powerless",
            "pressured": "burdened",
            "privileged": "entitled",
            "proud": "happy",
            "provoked": "angry",
            "punished": "hated",
            "put upon": "burdened",
            "quaking": "fearful",
            "quiescent": "apathetic",
            "rageful": "angry",
            "rapturous": "happy",
            "rated": "singled out",
            "reassured": "fearless",
            "reckless": "powerless",
            "redeemed": "singled out",
            "regretful": "sad",
            "rejected": "alone",
            "released": "free",
            "remorse": "sad",
            "replaced": "hated",
            "repulsed": "demoralized",
            "resentful": "angry",
            "resolute": "fearless",
            "respected": "esteemed",
            "responsible": "adequate",
            "restful": "fearful",
            "revered": "esteemed",
            "rueful": "sad",
            "sad": "sad",
            "satisfied": "happy",
            "saucy": "happy",
            "scared": "fearful",
            "secure": "fearless",
            "self-reliant": "fearless",
            "serene": "happy",
            "shaky": "fearful",
            "shamed": "sad",
            "shocked": "surprise",
            "significant": "esteemed",
            "singled out": "singled out",
            "skeptical": "anxious",
            "snoopy": "attracted",
            "somber": "sad",
            "sparkling": "happy",
            "spirited": "happy",
            "spiritless": "sad",
            "sprightly": "happy",
            "startled": "surprise",
            "stereotyped": "singled out",
            "stifled": "powerless",
            "stout hearted": "fearless",
            "strong": "independent",
            "suffering": "sad",
            "sulky": "sad",
            "sullen": "angry",
            "sunny": "happy",
            "surprised": "surprise",
            "suspicious": "anxious",
            "sympathetic": "codependent",
            "tense": "anxious",
            "terrified": "fearful",
            "terrorized": "fearful",
            "thankful": "happy",
            "threatened": "fearful",
            "thwarted": "powerless",
            "timid": "fearful",
            "timorous": "fearful",
            "torn": "derailed",
            "tortured": "sad",
            "tragic": "sad",
            "tranquil": "happy",
            "transported": "happy",
            "trapped": "entitled",
            "tremulous": "fearful",
            "tricked": "entitled",
            "turned on": "lustful",
            "unapproved of": "hated",
            "unbelieving": "anxious",
            "uncertain": "anxious",
            "unconcerned": "apathetic",
            "understood": "attached",
            "unfocussed": "lost",
            "unlovable": "hated",
            "unloved": "hated",
            "unmotivated": "apathetic",
            "unshackled": "free",
            "unsupported": "belittled",
            "up in arms": "angry",
            "upset": "fearful",
            "validated": "loved",
            "valued": "esteemed",
            "victimized": "sad",
            "violated": "cheated",
            "virulent": "angry",
            "vivacious": "happy",
            "vulnerable": "powerless",
            "wavering": "anxious",
            "weak": "powerless",
            "welcomed": "loved",
            "woebegone": "sad",
            "woeful": "sad",
            "worn down": "powerless",
            "worn out": "powerless",
            "worried": "fearful",
            "worshiped": "esteemed",
            "wrathful": "angry",
            "wronged": "singled out",
            "wrought up": "angry",
            "yearning": "lustful",
            "yellow": "fearful",
            "zealous": "attracted",
            "abandoned": "hated",
            "absolved": "singled out",
            "absorbed": "attracted",
            "abused": "powerless",
            "accepted": "loved",
            "aching": "sad",
            "acrimonious": "angry",
            "addicted": "codependent",
            "adequate": "adequate",
            "admired": "esteemed",
            "affectionate": "attached",
            "affronted": "singled out",
            "afraid": "fearful",
            "airy": "happy",
            "alone": "alone",
            "ambivalent": "bored",
            "apathetic": "apathetic",
            "apprehensive": "anxious",
            "arrogant": "independent",
            "ashamed": "embarrassed",
            "astonished": "surprise",
            "at ease": "safe",
            "attacked": "fearful",
            "audacious": "fearless",
            "autonomous": "free",
            "average": "average",
            "avid": "attracted",
            "baffled": "lost",
            "bashful": "powerless",
            "belittled": "belittled",
            "buoyant": "happy",
            "burdened": "burdened",
            "clouded": "sad",
            "committed": "focused",
            "compassionate": "attached",
            "compelled": "obsessed",
            "dauntless": "fearless",
            "debonair": "happy",
            "deceived": "entitled",
            "delighted": "ecstatic",
            "demoralized": "demoralized",
            "derailed": "derailed",
            "desirous": "attracted",
            "despairing": "sad",
            "devastated": "angry",
            "diffident": "fearful",
            "discredited": "belittled",
            "disheartened": "sad",
            "disinclined": "demoralized",
            "disorganized": "powerless",
            "downcast": "sad",
            "entitled": "entitled",
            "excited": "adequate",
            "exultant": "happy",
            "fidgety": "fearful",
            "frowning": "sad",
            "full of misgiving": "anxious",
            "great": "happy",
            "hapless": "sad",
            "hated": "hated",
            "heroic": "fearless",
            "hostile": "angry",
            "in despair": "sad",
            "indifferent": "bored",
            "infuriated": "angry",
            "insecure": "fearful",
            "inspired": "happy",
            "inspiring": "attracted",
            "judged": "singled out",
            "justified": "singled out",
            "laughting": "happy",
            "loved": "loved",
            "loving": "attached",
            "low": "sad",
            "lustful": "lustful",
            "manipulated": "cheated",
            "mumpish": "sad",
            "nosey": "attracted",
            "numb": "apathetic",
            "obliterated": "powerless",
            "peaceful": "happy",
            "petrified": "fearful",
            "piqued": "angry",
            "piteous": "sad",
            "powerless": "powerless",
            "questioning": "anxious",
            "rejected": "hated",
            "self-satisfied": "happy",
            "set up": "entitled",
            "shut out": "alone",
            "sorrowful": "sad",
            "spirited": "sad",
            "supported": "esteemed",
            "suspicious": "fearful",
            "terrific": "happy",
            "trapped": "entitled",
            "trembling": "fearful",
            "uncomfortable": "anxious",
            "underestimated": "belittled",
            "unhappy": "sad",
            "vindicated": "singled out",
            "worked up": "angry"
        }

    # convert text to lowercase
    def to_lower(self, text):
        return text.lower()

    # expand contractions
    def expand_contractions(self, text):
        expanded_text = ' '.join(self.contractions_dict.get(
            word, word) for word in text.split())
        return expanded_text

    # remove HTML tags
    def remove_html_tags(self, text):
        additional_terms_pattern = '|'.join(
            re.escape(term) for term in self.additional_html_terms)
        regex_pattern = rf'<(?:[^>]*?|({additional_terms_pattern}))>'
        clean_text = re.sub(regex_pattern, '', text)
        return clean_text

    # remove URLs
    def remove_urls(self, text):
        return re.sub(r'http\S+', '', text)

    # remove special characters
    def remove_special_characters(self, text):
        text = re.sub(r'[^a-zA-Z\s]', '', text)
        text = re.sub(r'\s+', ' ', text)
        return text.strip()

    # remove punctuation
    def remove_punctuation(self, text):
        text = re.sub(r'[^\w\s]', '', text)
        return text

    # remove emojis
    def remove_emojis(self, text):
        return emoji.demojize(text, delimiters=(" ", " "))

    # expand chat words
    def expand_chatwords(self, text):
        expanded_text = ' '.join(self.chat_words.get(word, word)
                                 for word in text.split())
        return expanded_text

    def expand_emotions(self, text):
        text = text.lower()
        for emotion, description in self.emotions_dict.items():
            text = text.replace(emotion, description)    
        return text

    # tokenize text
    def tokenize_text(self, text):
        tokenizer = RegexpTokenizer(r'\w+')
        tokens = tokenizer.tokenize(text)
        return tokens

    # remove stopwords
    def remove_stopwords(self, tokens):
        stop_words = set(stopwords.words('english'))
        filtered_tokens = [
            token for token in tokens if token.lower() not in stop_words]
        return filtered_tokens

    # stem tokens
    def stem_tokens(self, tokens):
        porter = PorterStemmer()
        stemmed_tokens = [porter.stem(token) for token in tokens]
        return stemmed_tokens

    # lemmatize tokens
    def lemmatize_tokens(self, tokens):
        lemmatizer = WordNetLemmatizer()
        lemmatized_tokens = [lemmatizer.lemmatize(token) for token in tokens]
        return lemmatized_tokens

    # remove negation
    def remove_negation(self, text):
        tokens = word_tokenize(text)
        stop_words = set(stopwords.words('english'))

        negations = {"not", "n't"}

        result_tokens = []
        negate = False
        for token in tokens:
            if token.lower() in negations:
                negate = True
                continue
            
            if negate and token.lower() in stop_words:
                negate = False
                continue

            if negate:
                antonyms = set()
                for syn in wordnet.synsets(token):
                    for lemma in syn.lemmas():
                        if lemma.antonyms():
                            antonyms.add(lemma.antonyms()[0].name())

                if antonyms:
                    result_tokens.append(min(antonyms, key=len))  # Adiciona o antônimo mais curto
                else:
                    result_tokens.append(token)
                negate = False
            else:
                result_tokens.append(token)

        return ' '.join(result_tokens)